language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
sudo: false
cache:
  directories:
    - node_modules
after_success: npm i coveralls && $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls
